version: '3.5'

services:
  anonymization_database:
    image: mongo:3.6.4
    container_name: anonymization_database
    volumes:
      - anonymization_database_data:/data/db
    ports:
      - 27017:27017
    networks:
      - anonymization_network
  anonymization_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: anonymization_server:latest
    container_name: anonymization_server
    depends_on:
      - anonymization_database
    ports:
      - 9137:9137
    networks:
      - anonymization_network

volumes:
  anonymization_database_data:
    driver: local

networks:
  anonymization_network:
    name: anonymization_network
    driver: bridge