/*
 * Data Anonymization Server
 *
 * This is a data anonymization server. You can set the anonymization requirements for the different datasets individually, and upload data to them. The uploaded data is anonymized on the server and can be then downloaded.
 *
 * API version: 0.1-alpha
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// CreateUploadSessionRequest is the JSON object the client sends to create an upload session
type CreateUploadSessionRequest struct {
	DatasetName string `json:"datasetName,omitempty"`
}

// CreateUploadSessionResponse is the JSON object the server sends back with the session id
type CreateUploadSessionResponse struct {
	SessionID string `json:"sessionId,omitempty"`
}

// UploadResponse is the JSON object the server sends back with the information about the upload
type UploadResponse struct {
	InsertSuccessful   bool   `json:"insertSuccessful"`
	FinalizeSuccessful bool   `json:"finalizeSuccessful"`
	Error              string `json:"error,omitempty"`
}
